# Generated by Django 4.2 on 2023-11-01 00:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Excerpt', models.CharField(max_length=200)),
                ('Image_name', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now=True)),
                ('Slug', models.SlugField(unique=True)),
                ('Content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to='blog.author')),
                ('Tag', models.ManyToManyField(to='blog.tag')),
            ],
        ),
    ]
