# Generated by Django 4.2 on 2023-11-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
