# Generated by Django 4.2 on 2023-11-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_first_name_author_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
